### ISSUE TITLE
Implement event source authentication and validation

### ISSUE THREAD

**Issue by markborkum** [pacifica/pacifica-notifications#26]
### Pacifica Notifications version
n/a

### Pacifica Core Software versions
n/a

### Platform Details
n/a

### Scenario:
The receiver should be able to authenticate and validate the event source for CloudEvents notification messages. For example, when the receiver registers a new subscription, the receiver may supply a nonce (e.g., a bearer token) that must be incorporated into the URI for the `/receive` endpoint or included as an HTTP header. Alternatively, the sender and receiver could use cryptography (i.e., payload signing).

### Steps to Reproduce:
n/a

### Expected Result:
n/a

### Actual Result:
n/a

**Comment by markborkum** [comment]
@dmlb2000 @kfox1111 @khm

This could be done by adding an `auth` attribute to the `pacifica.notifications.orm.EventMatch` class. 

Initially, the new field could store HTTP Basic or Bearer authentication information, used to augment the HTTP request to the CloudEvents notification receiver's HTTP endpoint.

The receiver, e.g., https://github.com/pacifica/pacifica-dispatcher, would also need to be modified.

**Comment by dmlb2000** [comment]
@markborkum I agree with this, I think the `auth` attribute should be a JSONField with some minimum schema so the code can be extended to include more authentication types for clients. Including either HTTP Basic or a shared key token should be first implementation. The thought is that complicated authentication mechanisms like OAuth would be able to be developed later.

**Comment by dmlb2000** [comment]
We should also reference the cloud event spec recommendations so everyone knows where they are at...

https://github.com/cloudevents/spec/blob/master/spec.md#privacy-and-security
